---
title: ComparaConta.com
url: https://comparaconta.com
baseurl: ""
github_repository: jmonteiro/comparaconta
github_url: https://github.com/jmonteiro/comparaconta

plugins:
  - jekyll-redirect-from
