---
title: ComparaConta.com
url: https://comparaconta.com
baseurl: ""
github_repository: jmonteiro/comparaconta
github_url: https://github.com/jmonteiro/comparaconta

exclude:
# Directories:
- bin
- node_modules
# Files:
- Gemfile*
- LICENSE
- Procfile.dev
- README.md
- package-lock.json
- package.json
- redirects.json
- tailwind.config.js

plugins:
- jekyll-redirect-from
