name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_WITHOUT: "test:development"
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4

      # - run: yarn install
      - run: node --version
      - run: npm install

      - name: Build
        env:
          BRIDGETOWN_ENV: production
          BUNDLE_WITHOUT: "test:development"
        run: bin/bridgetown deploy

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  # deploy:
  #   needs: build

  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: cloudflare
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
