name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: cloudflare
      url: https://comparaconta.com
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_WITHOUT: "test:development"
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install

      - name: Build
        env:
          BRIDGETOWN_ENV: production
          BUNDLE_WITHOUT: "test:development"
        run: bin/bridgetown deploy

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./output --project-name=comparaconta
